version: "2"
services:
  my:
    build: .
    container_name: client
    volumes:
    #- ./dist/:/usr/src/app/www/dist
    - client_deps:/usr/src/app/www/node_modules
    ports:
        - "4001:80"
    depends_on:
        - mongo
  
  mongo:
    image: mongo
    ports:
    - "27017:27017"

  # nginxmy:
  #  build: ./nginxmy
  #  ports:
  #      - "3001:80"
  #  links:
  #      - my
  #  volumes:
  #      - ./logsmy/nginx/:/var/log/nginx:cached

  # nginx1:
  #  build: ./nginx
  #  ports:
  #      - "3002:80"
  #  links:
  #      - my
  #  volumes:
  #      - ./logs/nginx/:/var/log/nginx:cached
  #       #- ./dist/:/var/www/

volumes:
  client_deps:
