version: "2"
services:
  my:
    build: .
    volumes:
    - ./:/usr/src/app
    ports:
        - "8080:3001"
    depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"

