version: "2"
services:
  # server:
  #   build: ./backend
  #   environment:
  #     - P_MONGO_URI=mongodb://mongoimage:27017/isawyou
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - node_modules:/usr/src/app/node_modules
  #   ports:
  #       - "8080:3001"
  #   depends_on:
  #       - mongo
  #
  # mongo:
  #   image: mongo
  #   volumes:
  #     - db_data:/data/db
  #   ports:
  #     - "27017:27017"

  client_dev:
    build: ./www
    container_name: client
    volumes:
    #- ./dist/:/usr/src/app/www/dist
    - client_deps:/usr/src/app/node_modules
    ports:
        - "4200:4200"

volumes:
  # node_modules:
  # db_data:
  client_deps:





#https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds

# version: "2"
# services:
#   backend:
#     build: ./backend
#     environment:
#        - P_MONGO_URI=mongodb://mongoimage:27017/isawyou
#     volumes:
#      - ./backend:/usr/src/app
#     ports:
#         - "3001:3001"
#     depends_on:
#       - mongo
#
#   mongo:
#     image: mongo
#     volumes:
#       - ./data:/data/db
#     ports:
#       - "27017:27017"
