version: "2"
services:
  backend:
    build: ./backend
    environment:
       - P_MONGO_URI=mongodb://mongoimage:27017/isawyou
    #container_name: backend
    #volumes:
    #  - ./backend:/usr/src/app
    ports:
        - "3001:3001"
    networks:
      - back-tier 
    depends_on:
        - mongoimage

  mongoimage:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
    networks:
      - back-tier 

networks:
  back-tier:
    driver: bridge

  # my:
  #   build: .
  #   container_name: client
  #   volumes:
  #   #- ./dist/:/usr/src/app/www/dist
  #   - client_deps:/usr/src/app/www/node_modules
  #   ports:
  #       - "4001:80"
   
  


  

  # nginxmy:
  #  build: ./nginxmy
  #  ports:
  #      - "3001:80"
  #  links:
  #      - my
  #  volumes:
  #      - ./logsmy/nginx/:/var/log/nginx:cached

  # nginx1:
  #  build: ./nginx
  #  ports:
  #      - "3002:80"
  #  links:
  #      - my
  #  volumes:
  #      - ./logs/nginx/:/var/log/nginx:cached
  #       #- ./dist/:/var/www/

# volumes:
#   client_deps:
